spring:
  application:
    name: MovieBase
  dataSource:
    url: jdbc:postgresql://ankush-db-5136.8nk.gcp-asia-southeast1.cockroachlabs.cloud:26257/defaultdb?sslmode=require&password=gqntwyTxjq5OEOZlpPqv8g&user=ankush
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
